name: Trippo

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make checksum executable
        run: chmod +x ./checksum.sh

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Install JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Generate cache key
        run: ./checksum.sh checksum.txt

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Build App
        uses: ./gradlew assembleDebug

      - name: Upload Sample Artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: apk
          path: app/build/outputs/apk/debug/*.apk
